### ISSUE TITLE
verify_mode in call to Net::HTTP.start

### ISSUE THREAD

**Issue by ghost** [sensu-plugins/sensu-plugins-uchiwa#4]
With version 0.0.4 running in embedded ruby provided by sensu-0.25.6-1 package, I got some errors on call to Net::HTTP.start:
undefined local variable or method `verify_mode'
https://github.com/sensu-plugins/sensu-plugins-uchiwa/blob/master/bin/check-uchiwa-health.rb#L82

After adding colon before "verify_mode", check is OK.

I did not try with SSL.

**Comment by jcastillocano** [comment]
I've tried that patch with HTTPS and it did work @GwennG, so +1 to this!

**Comment by sstarcher** [comment]
should be fixed by https://github.com/cstadach/sensu-plugins-uchiwa/pull/1
